name: Run comparing, categorizing, counting process
run-name: Run comparing, categorizing, counting process
on: 
  workflow_dispatch:
    inputs:
      nameMatchPcnt:
        description: Match percent for names
        default: '80'
        type: string
      addrMatchPcnt:
        description: Match percent for addresses
        default: '60'
        type: string
    
jobs:
  Process_input_file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name : Check ckeckout
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: compose kwargs line
        run: |
          import os
          def kwarg(a,v):
            if len(v.strip())>0:
              return "--"+a+" "+v
            else:
              return ""
          kw=''
          kw=kw+' '+kwarg('matchPcntAddress',str(${{ inputs.addrMatchPcnt }}))
          kw=kw+' '+kwarg('matchPcntName'   ,str(${{ inputs.nameMatchPcnt }}))
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f'kwargstring={kw}',file=fh)
        shell: python 
        id: kwargs
      - name: show kwarg line
        run: echo " ${{ steps.kwargs.outputs.kwarstring }}"
      - name: execute py script # run main.py
        run: python Categorize.py TestFile.xlsx --matchPcntName --limitUniqueClients 2 ${{ steps.kwargs.outputs.kwargstring }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.xlsx
          git commit  -m "generated output" 
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
