name: Run comparing, categorizing, counting process
run-name: Run comparing, categorizing, counting process
on: 
  workflow_dispatch:
    inputs:
      inputFileName:
        description: Input file name
        default: 'TestFile.xlsx'
        type: string
      exemptionsFile:
        description: Exemptions file name (exemptions.txt if not specified)
        default: ''
        type: string
      nameMatchPcnt:
        description: Match percent for names (80  if not specified)
        default: ''
        type: string
      addrMatchPcnt:
        description: Match percent for addresses (60  if not specified)
        default: ''
        type: string
      limitClientsToProcess:
        description: Process will be stopped after this number of same client groups identified
        default: ''
        type: string
      limitInputRows:
        description: Process will be stopped after this number of rows taken from input file
        default: ''
        type: string
      skipFirstRows:
        description: Process will start after this number of rows skipped from beginnig of input file
        default: ''
        type: string
      

    
jobs:
  Process_input_file:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name : Check ckeckout
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: compose kwargs line
        run: |
          import os
          def kwarg(a,v):
            if len(v.strip())>0:
              return "--"+a+" "+v
            else:
              return ""
          kw=''
          kw=kw+' '+kwarg('matchPcntAddress'   ,str(${{ inputs.addrMatchPcnt }}))
          kw=kw+' '+kwarg('matchPcntName'      ,str(${{ inputs.nameMatchPcnt }}))
          kw=kw+' '+kwarg('limitUniqueClients' ,str(${{ inputs.limitClientsToProcess }}))
          kw=kw+' '+kwarg('limitInputRows'     ,str(${{ inputs.limitInputRows }}))
          kw=kw+' '+kwarg('skipFirstRows'      ,str(${{ inputs.skipFirstRows }}))
          with open(os.environ['GITHUB_OUTPUT'], 'a') as fh:
            print(f'kwargstring={kw}',file=fh) 
        shell: python 
        id: kwargs
      - name: show kwarg line
        run: echo " ${{ steps.kwargs.outputs.kwarstring }}"
      - name: execute py script # run main.py
        run: python Categorize.py ${{ inputs.inputFileName }} ${{ steps.kwargs.outputs.kwargstring }}
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.xlsx
          git commit  -m "generated output" 
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main 
