name: Parse DBT materializations
run-name: Parsing materializations after push by ${{ github.actor }} 🚀
on: 
  workflow_dispatch:
jobs:
  Parse-Materializations:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name : Check ckeckout
        run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11' # install the python version needed
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: execute py script # run main.py
        run: python parse_project_materializations.py
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add DBT_Materializations.*
          git commit  -m "updated materializations" 
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: new_projects 
